ALTER TABLE dim_spatial
    ADD COLUMN IF NOT EXISTS emd_code TEXT,
    ADD COLUMN IF NOT EXISTS emd_name TEXT,
    ADD COLUMN IF NOT EXISTS sig_code TEXT,
    ADD COLUMN IF NOT EXISTS sig_name TEXT,
    ADD COLUMN IF NOT EXISTS sido_code TEXT,
    ADD COLUMN IF NOT EXISTS sido_name TEXT;
