DOMAIN_INPUT_SCHEMA = {
    "sales": {
        "time_column": "STD_YM",
        "spatial_candidates": ["SGG_NAME", "LDONG_NAME", "LDONG", "SGG_CODE"],
        "category_column": "SCLS_NM",
        "category_fields": {
            "large": "LCLS_NM",
            "medium": "MCLS_NM",
            "small": "SCLS_NM",
        },
        "sales_prefixes": ["MAN_SALE_AMT_", "WMAN_SALE_AMT_"],
        "count_prefixes": ["MAN_APV_CNT_", "WMAN_APV_CNT_"],
    },
    "telco": {
        "time_column": "CRTR_YM",
        "day_column": "DAY_CNT",
        "spatial_column": "VST_SGG_CD",
        "male_prefix": "ML_VST_PPLTN_",
        "female_prefix": "FM_VST_PPLTN_",
    },
    "telco_grid": {
        "date_column": "CRTR_YMD",
        "month_column": "CRTR_YM",
        "spatial_column": "SM_LC_CD",
        "coord_x_column": "COORD_X",
        "coord_y_column": "COORD_Y",
        "male_prefixes": ["VST_ML_PPLTN_CNT_"],
        "female_prefixes": ["VST_FM_PPLTN_CNT_"],
    },
    "sungnam_service": {
        "inflow": {
            "time_column": "STD_YM",
            "date_column": "STD_YMD",
            "hour_column": "TIME",
            "spatial_column": "HCODE",
            "inflow_column": "INFLOW_CD",
            "home_column": "H_POP",
            "work_column": "W_POP",
            "visit_column": "V_POP",
        },
        "sex_age": {
            "time_column": "STD_YM",
            "date_column": "STD_YMD",
            "hour_column": "TIME",
            "sex_age_column": "SEX_AGE",
            "spatial_column": "HCODE",
            "home_column": "H_POP",
            "work_column": "W_POP",
            "visit_column": "V_POP",
        },
        "pcell_sex_age": {
            "time_column": "STD_YM",
            "date_column": "STD_YMD",
            "spatial_column": "HCODE",
            "coord_x_column": "X_COORD",
            "coord_y_column": "Y_COORD",
            "male_prefix": "M_",
            "female_prefix": "W_",
        },
        "pcell": {
            "time_column": "STD_YM",
            "date_column": "STD_YMD",
            "spatial_column": "HCODE",
            "time_prefix": "TIME_",
            "coord_x_column": "X_COORD",
            "coord_y_column": "Y_COORD",
        },
        "unique": {
            "time_column": "STD_YM",
            "date_column": "STD_YMD",
            "spatial_column": "SGNG_CD",
            "inflow_column": "INFLOW_CD",
            "male_prefix": "M_",
            "female_prefix": "W_",
        },
    },
}
